### ISSUE TITLE
System.NotImplementedException in Xamarin UWP app

### ISSUE THREAD

**Issue by yogiderek** [alexrainman/Plugin.KeyChain#1]
Hi

I am getting the following error in my Xamarin UWP app when trying to use CrossKeyChain.Current.SetKey

"An exception of type 'System.NotImplementedException' occurred in Plugin.KeyChain.dll but was not handled in user code

Additional information: This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation."

Plugin.KeyChain is installed in all projects. I have tried uninstalling and re installing the plugin and deleting all bin/obj folders and rebuilding but the problem still exists.

I am assuming this is because the _Implementation_ variable in CrossKeyChain class is null because KeyChainImplementation failed. 

For reference, I have Plugin.KeyChain & Plugin.KeyChain.Abstractions in all projects EXCEPT the UWP where i just have Plugin.KeyChain. 

Thank you for looking into this issue.

**Comment by alexrainman** [comment]
Yes, basically the plugin has not UWP implementation. I will put it on my schedule and try to solve it as soon as possible. Thanks

**Comment by yogiderek** [comment]
Thanks, looking forward to using it. I found this article on plugins, can you recommend any others

Cross-platform NuGet Packages
https://blog.kloud.com.au/2015/05/12/xamarin-plugins/

**Comment by alexrainman** [comment]
It depends what you want to do. Giving you couple of examples:

- Dialogs: Acr.UserDialogs (dialog service from viewmodels)
- Sqlite: SqliteNetExtensions (helps to represent, insert and read complex JSON structures from local storage)

I ship some useful plugins also:

- SegmentedControl for Xamarin.Forms
- CarouselView control for Xamarin.Forms
- Sqlite.Net.Cipher

Cheers!

**Comment by alexrainman** [comment]
Released.
